# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-06-27T12:56:15+00:00

from __future__ import annotations


from pydantic import BaseModel, Field, constr


class HereBeDragons(BaseModel):
    __root__: constr(regex=r"here")


class MoreValues(BaseModel):
    name: str
    age: int | None = None


class PettyNumber(BaseModel):
    __root__: constr(regex=r"[0-9]{2-8}")


class Values(BaseModel):
    name: str


class MoreValuesRefext(Values):
    size: int | None = None


class PassMe(BaseModel):
    mangled_string: PettyNumber | HereBeDragons
    confused_values: Values | MoreValues | MoreValuesRefext = Field(
        ..., description="values is matched first no matter what"
    )
    nice_values: MoreValuesRefext | MoreValues | Values = Field(
        ...,
        description="more-values is matched first "
        "- it may also match if the schema does",
    )
