# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-06-27T14:56:41+00:00

from typing import Annotated


from pydantic import BaseModel, Field, StringConstraints


type HereBeDragons = Annotated[str, StringConstraints(pattern=r"here")]
type PrettyNumber = Annotated[str, StringConstraints(pattern=r"[0-9]{2,8}")]


class MoreValues(BaseModel):
    name: str
    age: int | None = None


class Values(BaseModel):
    name: str


class MoreValuesRefext(Values):
    size: int | None = None


class PassMe(BaseModel):
    mangled_string: PrettyNumber | HereBeDragons | None = None
    confused_values: Values | MoreValues | MoreValuesRefext | None = Field(
        None, description="values is matched first no matter what"
    )
    nice_values: MoreValuesRefext | MoreValues | Values | None = Field(
        None, description="more-values is matched first"
    )
