# generated by datamodel-codegen:
#   filename:  openapi.broken_string.yaml
#   timestamp: 2024-08-09T15:08:11+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, RootModel, constr


class HereBeDragons(RootModel[constr(pattern=r'here')]):
    root: constr(pattern=r'here')


class PettyNumber(RootModel[constr(pattern=r'[0-9]{2,8}')]):
    root: constr(pattern=r'[0-9]{2,8}')


class PassString(BaseModel):
    mangled_string_one: Optional[Union[PettyNumber, HereBeDragons]] = None
    mangled_string_any: Optional[Union[PettyNumber, HereBeDragons]] = None
