# generated by datamodel-codegen:
#   filename:  openapi.broken_string.yaml
#   timestamp: 2024-08-12T14:10:27+00:00

from __future__ import annotations


from pydantic import BaseModel, RootModel, constr


class HereBeDragons(RootModel[constr(pattern=r"here")]):
    root: constr(pattern=r"here")


class PettyNumber(RootModel[constr(pattern=r"[0-9]{2,8}")]):
    root: constr(pattern=r"[0-9]{2,8}")


class PassString(BaseModel):
    mangled_string_one: PettyNumber | HereBeDragons | None = None
    mangled_string_any: PettyNumber | HereBeDragons | None = None
