# generated by datamodel-codegen:
#   filename:  openapi.ConfusedValues.yaml
#   timestamp: 2024-08-07T13:30:37+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, Field


class MoreValues(BaseModel):
    name: str
    age: Optional[int] = None


class Values(BaseModel):
    name: str


class MoreValuesRefext(Values):
    size: Optional[int] = None


class PassMe(BaseModel):
    confused_values: Optional[Union[Values, MoreValues, MoreValuesRefext]] = Field(
        None, description='values is matched first no matter what'
    )
    nice_values: Optional[Union[MoreValuesRefext, MoreValues, Values]] = Field(
        None, description='more-values is matched first'
    )
