# generated by datamodel-codegen:
#   filename:  openapi.ConfusedValues.yaml
#   timestamp: 2024-08-07T13:30:37+00:00

from __future__ import annotations


from pydantic import BaseModel, Field


class MoreValues(BaseModel):
    name: str
    age: int | None = None


class Values(BaseModel):
    name: str


class MoreValuesRefext(Values):
    size: int | None = None


class PassMe(BaseModel):
    confused_values: Values | MoreValues | MoreValuesRefext | None = Field(
        None, description="values is matched first no matter what"
    )
    nice_values: MoreValuesRefext | MoreValues | Values | None = Field(
        None, description="more-values is matched first"
    )
