# generated by datamodel-codegen:
#   filename:  openapi.ratings.yaml
#   timestamp: 2024-08-12T14:10:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class NamedRating(BaseModel):
    name: str
    rating: Optional[int] = Field(None, description='may be left out')


class PatchRatingNumber(BaseModel):
    rating: int = Field(..., description='this one needs a value')
