openapi: 3.0.0
info:
  title: Broken Examples Home
  version: 0.0.0
tags: []
paths:
  /value-order-matters:
    get:
      operationId: OrderOfValues_get
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PassMe'
components:
  schemas:
    MoreValues:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        age:
          type: integer
    MoreValuesRefext:
      type: object
      properties:
        size:
          type: integer
      allOf:
        - $ref: '#/components/schemas/Values'
    PassMe:
      type: object
      properties:
        confused_values:
          anyOf:
            - $ref: '#/components/schemas/Values'
            - $ref: '#/components/schemas/MoreValues'
            - $ref: '#/components/schemas/MoreValuesRefext'
          description: values is matched first no matter what
        nice_values:
          anyOf:
            - $ref: '#/components/schemas/MoreValuesRefext'
            - $ref: '#/components/schemas/MoreValues'
            - $ref: '#/components/schemas/Values'
          description: more-values is matched first
    Values:
      type: object
      required:
        - name
      properties:
        name:
          type: string
servers:
  - url: https://example.com
    description: The service endpoint
    variables: {}
