openapi: 3.0.0
info:
  title: Broken Examples Home
  version: 0.0.0
tags: []
paths:
  /string-example:
    get:
      operationId: Mangled_get
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PassString'
components:
  schemas:
    HereBeDragons:
      type: string
      pattern: here
    PassString:
      type: object
      properties:
        mangled_string_one:
          oneOf:
            - $ref: '#/components/schemas/PettyNumber'
            - $ref: '#/components/schemas/HereBeDragons'
        mangled_string_any:
          anyOf:
            - $ref: '#/components/schemas/PettyNumber'
            - $ref: '#/components/schemas/HereBeDragons'
    PettyNumber:
      type: string
      pattern: '[0-9]{2,8}'
servers:
  - url: https://example.com
    description: The service endpoint
    variables: {}
