# coding: utf-8

# flake8: noqa
"""
    rating storage

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from oapi_codegen.ratings.models.named_rating import NamedRating
from oapi_codegen.ratings.models.patch_rating_number import PatchRatingNumber
from oapi_codegen.ratings.models.ratings_update_request import RatingsUpdateRequest
