# coding: utf-8

"""
    Broken Examples Home

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from oapi_codegen_broken_string.models.pass_string_mangled_string_any import PassStringMangledStringAny
from oapi_codegen_broken_string.models.pass_string_mangled_string_one import PassStringMangledStringOne
from typing import Optional, Set
from typing_extensions import Self

class PassString(BaseModel):
    """
    PassString
    """ # noqa: E501
    mangled_string_one: Optional[PassStringMangledStringOne] = None
    mangled_string_any: Optional[PassStringMangledStringAny] = None
    __properties: ClassVar[List[str]] = ["mangled_string_one", "mangled_string_any"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PassString from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mangled_string_one
        if self.mangled_string_one:
            _dict['mangled_string_one'] = self.mangled_string_one.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mangled_string_any
        if self.mangled_string_any:
            _dict['mangled_string_any'] = self.mangled_string_any.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PassString from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mangled_string_one": PassStringMangledStringOne.from_dict(obj["mangled_string_one"]) if obj.get("mangled_string_one") is not None else None,
            "mangled_string_any": PassStringMangledStringAny.from_dict(obj["mangled_string_any"]) if obj.get("mangled_string_any") is not None else None
        })
        return _obj


