# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2024-06-27T14:56:41+00:00

from typing import Annotated


from pydantic import BaseModel, StringConstraints


type HereBeDragons = Annotated[str, StringConstraints(pattern=r"here", strict=True)]
type PrettyNumber = Annotated[
    str, StringConstraints(pattern=r"[0-9]{2,8}", strict=True)
]


class PassString(BaseModel):
    mangled_string: PrettyNumber | HereBeDragons | None = None
